### ISSUE TITLE
Move 'command-line-args' to dependencies

### ISSUE THREAD

**Issue by craigmr** [paulbrom/hmr-redux-mapper#2]
I removed `command-line-args` from my project dependency and started receiving the following error
```bash
Error: Cannot find module 'command-line-args'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at n (/Users/craigs/repos/ad-builder-ui/node_modules/hmr-redux-mapper/bin/hmr-redux-mapper.js:1:818)
    at /Users/craigs/repos/ad-builder-ui/node_modules/hmr-redux-mapper/bin/hmr-redux-mapper.js:1:1009
    at Object.1.command-line-args (/Users/craigs/repos/ad-builder-ui/node_modules/hmr-redux-mapper/bin/hmr-redux-mapper.js:1:1238)
    at n (/Users/craigs/repos/ad-builder-ui/node_modules/hmr-redux-mapper/bin/hmr-redux-mapper.js:1:958)
    at e (/Users/craigs/repos/ad-builder-ui/node_modules/hmr-redux-mapper/bin/hmr-redux-mapper.js:1:1125)
    at Object.<anonymous> (/Users/craigs/repos/ad-builder-ui/node_modules/hmr-redux-mapper/bin/hmr-redux-mapper.js:1:1142)
```

Moving `command-line-args` to a dependency instead of devDependency should fix the issue.

**Comment by craigmr** [comment]
Thanks Paul!
